apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: niajfe0v3-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:4df221bc91ee2442ac2823b31fc3f34744d78a90@sha256:4ed4c2f1889ebb7c18a8caabc32d7966ed880007b223e8328215f0c016f9bfe5
          name: container-image
